version: "3.7"
services:
  db:
    image: "postgres:11.2"
    container_name: "drgc_postgres1"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data
volumes:
  postgres_data1:
    name: drgc_postgres_data1