# Generated by Django 3.1.1 on 2020-09-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
